// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectedDirectory() {
  return window['go']['main']['App']['SelectedDirectory']();
}

export function StartHTTPServer() {
  return window['go']['main']['App']['StartHTTPServer']();
}

export function StopHTTPServer() {
  return window['go']['main']['App']['StopHTTPServer']();
}
