// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http} from '../models';

export function AutoDetectDraftRootPath():Promise<string>;

export function HandleDraft(arg1:http.ServeMux):Promise<void>;

export function HandleDrafts(arg1:http.ServeMux):Promise<void>;

export function HandleFuncWarp(arg1:http.ServeMux):Promise<void>;

export function HandleHome(arg1:http.ServeMux):Promise<void>;

export function SelectedDirectory():Promise<string>;

export function SendLogsToPage(arg1:string):Promise<void>;

export function SetDraftRootPath(arg1:string):Promise<string>;

export function StartHTTPServer():Promise<void>;

export function StopHTTPServer():Promise<void>;
