// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HandleDraft(arg1) {
  return window['go']['main']['App']['HandleDraft'](arg1);
}

export function HandleDrafts(arg1) {
  return window['go']['main']['App']['HandleDrafts'](arg1);
}

export function HandleFuncWarp(arg1) {
  return window['go']['main']['App']['HandleFuncWarp'](arg1);
}

export function HandleHome(arg1) {
  return window['go']['main']['App']['HandleHome'](arg1);
}

export function SelectedDirectory() {
  return window['go']['main']['App']['SelectedDirectory']();
}

export function StartHTTPServer() {
  return window['go']['main']['App']['StartHTTPServer']();
}

export function StopHTTPServer() {
  return window['go']['main']['App']['StopHTTPServer']();
}
