name: Wails Build
on:
  push:
    branches:
      - main
jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Copilot for Windows
        uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: jianyingpro-batch-keyframe-copilot
          build-platform: windows/amd64
          package: false
          nsis: true
      - name: show tree
        run: ls -R
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./build/bin/*.exe
          name: windows

  build_macos_amd64:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Copilot for macOS
        uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: jianyingpro-batch-keyframe-copilot
          build-platform: darwin/amd64
          package: false
          codesign: false
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./build/bin/*
          name: macos_amd64
  build_macos_arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Copilot for macOS
        uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: jianyingpro-batch-keyframe-copilot
          build-platform: darwin/arm64
          package: false
          codesign: false
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./build/bin/*
          name: macos_arm64
  upload:
    needs: [build_windows, build_macos_amd64, build_macos_arm64]
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4.1.7
      - name: show tree
        run: ls -R
      - name: compress macos
        run: |
          cd macos_amd64
          zip -r jianyingpro-batch-keyframe-copilot.zip jianyingpro-batch-keyframe-copilot.app
          cd ../macos_arm64
          zip -r jianyingpro-batch-keyframe-copilot.zip jianyingpro-batch-keyframe-copilot.app
      - name: Upload Windows Copilot
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.ACCOUNTID }}
          r2-access-key-id: ${{ secrets.ACCESSKEY }}
          r2-secret-access-key: ${{ secrets.SECRETKEY }}
          r2-bucket: ${{ secrets.BUCKET }}
          source-dir: ./windows
          destination-dir: jianyingpro-batch-keyframe-copilot/windows/prod/x64
      - name: Upload MacOS AMD64 Copilot
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.ACCOUNTID }}
          r2-access-key-id: ${{ secrets.ACCESSKEY }}
          r2-secret-access-key: ${{ secrets.SECRETKEY }}
          r2-bucket: ${{ secrets.BUCKET }}
          source-dir: ./macos_amd64
          destination-dir: jianyingpro-batch-keyframe-copilot/macos/prod/amd64
      - name: Upload MacOS ARM64 Copilot
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.ACCOUNTID }}
          r2-access-key-id: ${{ secrets.ACCESSKEY }}
          r2-secret-access-key: ${{ secrets.SECRETKEY }}
          r2-bucket: ${{ secrets.BUCKET }}
          source-dir: ./macos_arm64
          destination-dir: jianyingpro-batch-keyframe-copilot/macos/prod/arm64